version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: ./config/docker/dev/Dockerfile
    image: cth/web
    environment:
    - CONTACT_RECIPIENT=mail@gronows.com
    ports:
    - "8001:80"
    stdin_open: true
    tty: true
