# Variables
substitutions:
  _APP_NAME: cthdb-vue
  _INIT_NAME: cthdb-init

steps:
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - https://github.com/online-ventures/$_APP_NAME.git

# Pull previous vue docker image
- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - 'gcr.io/$PROJECT_ID/$_APP_NAME:latest'

# Build current vue docker image
- name: gcr.io/cloud-builders/docker
  dir: $_APP_NAME
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME:latest',
    '-t', 'gcr.io/$PROJECT_ID/$_APP_NAME:$COMMIT_SHA',
    '-f', 'config/docker/web/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/$_APP_NAME:latest',
    '.']
  timeout: 600s

# Push vue docker image
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - 'gcr.io/$PROJECT_ID/$_APP_NAME:latest'

# Pull previous init docker image
- name: gcr.io/cloud-builders/docker
  args:
  - pull
  - 'gcr.io/$PROJECT_ID/$_INIT_NAME:latest'

# Build current init docker image
- name: gcr.io/cloud-builders/docker
  dir: $_APP_NAME
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$_INIT_NAME:latest',
    '-t', 'gcr.io/$PROJECT_ID/$_INIT_NAME:$COMMIT_SHA',
    '-f', 'config/docker/db/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/$_INIT_NAME:latest',
    '.']
  timeout: 600s

# Push init docker image
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - 'gcr.io/$PROJECT_ID/$_INIT_NAME:latest'

# Ensure it has both latest tag and commit sha tag
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - 'gcr.io/$PROJECT_ID/$_INIT_NAME:$COMMIT_SHA'

# Get access key
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=config/cloudbuild/token.enc
  - --plaintext-file=/root/env
  - --location=global
  - --keyring=cloud-build
  - --key=digital-ocean-access-key
  volumes:
  - name: 'home'
    path: /root

# Set up kubectl
- name: 'gcr.io/web-online-ventures/curl'
  args: ['bash', 'config/cloudbuild/curl-config']
  volumes:
  - name: 'home'
    path: /root
  - name: '1001'
    path: /home/1001

# Update cluster pods
- name: 'bitnami/kubectl'
  args:
    - '--kubeconfig'
    - '/home/1001/kube'
    - 'set'
    - 'image'
    - 'deploy/cthvue'
    - 'vue=gcr.io/$PROJECT_ID/$_APP_NAME:$COMMIT_SHA'
    - '--namespace=default'
  volumes:
  - name: '1001'
    path: /home/1001

# Save this build as well according to commit sha
images:
- 'gcr.io/$PROJECT_ID/$_APP_NAME:$COMMIT_SHA'
