version: '3.6'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - "5485:5432"
    restart: always
    volumes:
    - db-data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v1.2.2
    ports:
    - "8083:8080"
    depends_on:
    - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_LOG_LEVEL: info
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,http-log,query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDBzCCAe+gAwIBAgIJH9golvoOY38lMA0GCSqGSIb3DQEBCwUAMCExHzAdBgNV\nBAMTFmFsbHN0YXJzLWRldi5hdXRoMC5jb20wHhcNMjAwNTI2MTQ0MTA0WhcNMzQw\nMjAyMTQ0MTA0WjAhMR8wHQYDVQQDExZhbGxzdGFycy1kZXYuYXV0aDAuY29tMIIB\nIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxc6fK/1Na021OhApq3AefADl\n/lnB+Tc11mLlmwCA0NrDqwYuQN9tmWn3J4KCWyR4yd2/INYBFewIRWHZPKwz+n9a\nvqLlhWzR21N2l38VIsE4HmzfJSkiifS7Aq3R2JXowzbFp/IhXN724VW83/+nrFrF\nfciRLxM4WlVHhvD/N1ph0MKO+h8TbL2FtyMNugGo/7docWvUracy4txpxFXj0//l\n2bfUcc18kv8m04Gz+3XBOZKFbtgoShl1XGN/vtj0hvlttHritdLMLoUJtRPt5gNK\nGbKNN32sAJh2Wj4M0HlwG1eB28mXb1yum7Ofm/rex3Vhs6DfSbMpD+QlrWWr5wID\nAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSS3GwZvUCKfOr0b3Kg\nGmZgVQ9cxDAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBAGHF6/ij\nfkdW24EGFWmYpH7x7/QSp7RAnhx5GGmvrtE1SqwBVHFyLlt7LQL0qy+mS8tVw9/H\nAr8dik8PboSrhj3ykLRsgZLU9JKGSiA6GacI398fPIYVZX49P38Ov5iB38YiZZ8R\nfbGDTH2LMXfghkv7HLYmxkkEg9avbdF1/t65dQH8tmfa46FnWgegPI0d46j14rJo\nYhX/FtN7fDk8cLuGK6035BXSoYrCoNBhS/IQDBCVxFTRI1R//JZ75hoz86Ui+5qb\n0EzdD6wVc/S/ysnMPP9g/3GQ9xedUa4DvfJE3yh16VfeMMCHEfKG9sowvlY8gAZK\nZLmOwrd6GGC9/74=\n-----END CERTIFICATE-----"}'
      ADD_EDITOR_URL: add-editor

  add-editor:
    image: gcr.io/web-online-ventures/stars-add-editor:latest
    restart: always
    volumes:
    - "./secrets:/var/openfaas/secrets"

volumes:
  db-data:
    name: cth-db
