version: '3.6'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - "5485:5432"
    restart: always
    volumes:
    - db-data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v1.2.1
    ports:
    - "8083:8080"
    depends_on:
    - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_LOG_LEVEL: info
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,http-log,query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIC/zCCAeegAwIBAgIJU+JT1e8G7unEMA0GCSqGSIb3DQEBCwUAMB0xGzAZBgNV\nBAMTEmFsbHN0YXJzLmF1dGgwLmNvbTAeFw0yMDA1MTAxMzI1MDlaFw0zNDAxMTcx\nMzI1MDlaMB0xGzAZBgNVBAMTEmFsbHN0YXJzLmF1dGgwLmNvbTCCASIwDQYJKoZI\nhvcNAQEBBQADggEPADCCAQoCggEBAKmFs7hYsu54LL0EY1sy1UXLABjQljGn7fev\nMT/onLuFW2V9U0VzG+tqp5nhkMj+7dQArMTZIgVdL/YOyfNjw1x1hunnQBwBhw9s\nH9TqRrGhjSAzeJnLz5ueqmILJeVMQZyu0g73tlz3Yi8tVC00+IkQaXD6DbjOndic\ne8Bldx+vpsaePw/JSF9eW6ZgbG7MAOmjKwuyx0MOYm37D7nWMzrWCxPLXDXwnUMY\nFOlOioUzVRgCtiy0wLvlWdPdqZ1ErCQdrVRmv3yxyM4IYL0oYOPMTpLIK0XUvCCI\n6UFLXxUNMTWiU3wpOCj6YcbqNHc6YE54+2UF8pZfUPUFG77ktoECAwEAAaNCMEAw\nDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUFfGx182+O7twqbO9c+UfWMfeL70w\nDgYDVR0PAQH/BAQDAgKEMA0GCSqGSIb3DQEBCwUAA4IBAQATd+kauzlCJjLIIDHR\nU1Uz8qwjhAvIJjaB3palKHPImpi5uxwXk7bk9Y26uQXoPya0R+BemBiiW29lO5UU\nTeNSZ8Ue9RcW1uoAi/Z9WvRugabv5VjZWeUPo5y4NAB6/Xo4bEpBHLANL0TwL8Bu\nBGIUc16K01cW4rZ228fmvZDAxb4rXUWcOe/0fc7oni8a8PzVqMg9PFJxrApDuWgd\nILQGH4XJIvgvA3kpJycEfrXq86HD0oPiCY4CuZx/tCAPAqBpAZWDGWndVxDoOrds\n5dx0i93vdxlsI1XrPFpNp3bX08KstWyz7TashEeJtw1556cQtIqMAITSVzmKAOvT\nHC82\n-----END CERTIFICATE-----"}'
      ADD_EDITOR_URL: add-editor

  add-editor:
    image: gcr.io/web-online-ventures/stars-add-editor:latest
    restart: always
    volumes:
    - "./secrets:/var/openfaas/secrets"

volumes:
  db-data:
    name: cth-db
